### ISSUE TITLE
Will it be supported for Polymer 1.0+ ?

### ISSUE THREAD

**Issue by hectorguo** [googlearchive/icon-transition#7]
I notice that this element is depended on version 0.5. And the APIs of Polymer 1.0+ have been changed.  
I wonder if this element can be implemented into 1.0+ version. 

It's really amazing. Hope it can be considered in version 1.0+  :+1:

**Comment by whalliburton** [comment]
I also would use this if if was available for Polymer 1.0.

**Comment by nalbion** [comment]
It is now

**Comment by BorntraegerMarc** [comment]
@nalbion will it be supported for Polymer 2+? :)

**Comment by nalbion** [comment]
@BorntraegerMarc it will be if you port it ;-)

**Comment by BorntraegerMarc** [comment]
@nalbion Done 😄 https://github.com/PolymerLabs/icon-transition/pull/8
